# Generated by Django 5.0.6 on 2024-05-23 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roles', models.CharField(max_length=7)),
                ('phone', models.CharField(max_length=8)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subjectId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.course')),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('contentid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('cours', 'Cours'), ('td', 'Travaux Dirigés'), ('tp', 'Travaux Pratiques'), ('exam', 'Examen')], default='cours', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.course')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.subject')),
            ],
        ),
    ]
